server:
  port: 12346

spring:
  application:
    name: provider-b
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: qwe123@@

dubbo:
  scan:
    base-packages: indi.wuyue.hmily.dubbo.provider.b.rpc
  protocol:
    name: dubbo
    port: 20001
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

